### PR TITLE
Feature/10 tidy up our new session store to remove vacancy form data

### PR DESCRIPTION
**Pull request by despo**

### CODE REVIEW

**Comment by despo** [comment]
[Tidy up our new session store to remove vacancy form data](https://trello.com/c/CktZBfOy/10-tidy-up-our-new-session-store-to-remove-vacancy-form-data)

**Comment by despo** [comment]
On rebuild, the new build doesnt map to the PR -
https://eu-west-2.console.aws.amazon.com/codebuild/home?region=eu-west-2#/projects/tvs2-pull-requests/view

@tahb @Stretch96

**Comment by tahb** [comment]
Freezing this PR in the hope that Chris or Bob can take a look at this bug with retrying failed builds.

**Comment by tahb** [comment]
@despo I had a quick go at trying to replicate the build retry issue you noticed. I've not been able to do it. When I kick a change off via git (for this PR) and then retry manually through the AWS console I see the following:

screen shot 2018-04-09 at 15 03 28

What did you see? If you see it again could you screenshot it so we can see the problem too.

**Pull request merged**
