### PR TITLE
Feature/763 adding sharing buttons

### PR DESCRIPTION
**Pull request by mingoland**
## Trello card URL:
https://trello.com/c/RxJ1C17j/763-optimise-share-my-job-to-make-it-clearer-for-hiring-staff-users-that-they-can-share-the-job-they-have-created-on-social-media

## Changes in this PR:
- Add sharing buttons to job sharing box of job pages in the publishing view
- Add sharing buttons to the bottom of job pages in the publishing view
- Add sharing buttons to the bottom of job pages in the public view
- Add sharing buttons to the bottom of mobile version of job pages in the public view

### Before (Share this job box)
screenshot-share-buttons-box-before

### After (Share this job box)
screenshot-share-buttons-box-after

### Before (Footer)
screenshot-share-buttons-footer-before

### After (Footer)
screenshot-share-buttons-footer-after

### Before (mobile)
screenshot-share-buttons-mobile-before

### After (mobile)
screenshot-share-buttons-mobile-after

### CODE REVIEW

**Comment by mingoland** [comment]
[Optimise 'Share my job' to make it clearer for hiring staff users that they can share the job they have created on social media](https://trello.com/c/RxJ1C17j/763-optimise-share-my-job-to-make-it-clearer-for-hiring-staff-users-that-they-can-share-the-job-they-have-created-on-social-media)

**Comment by robbiepaul** [comment]
I added a commit to track clicks on the share buttons

**Comment by robbiepaul** [comment]
@tahb I added a commit to remove the LinkedIn button

**Comment by tahb** [comment]
@robbiepaul Thank you for that. I wonder if we could squash that last commit into https://github.com/dxw/teacher-vacancy-service/pull/812/commits/897dcd710de480a4593c9e243ad1797d673c8ebf and remove the need for https://github.com/dxw/teacher-vacancy-service/pull/812/commits/cedc83dca1dce5bd52c73a37df8d8c53fc65679b completely?

**Comment by robbiepaul** [comment]
Yeah I did think that, but then I thought if the user need for LinkedIn sharing ever arrises we could simply revert that commit

**Pull request merged**
