### PR TITLE
[757] Remove wasteful memory allocations

### PR DESCRIPTION
**Pull request by tahb**
## Trello card URL:
https://trello.com/c/yeyEZCG7

## Changes in this PR:
Whilst investigating high memory usage and a suspected memory leak I found exponential memory growth in some parts of the code using [derailed_benchmarks](https://github.com/schneems/derailed_benchmarks).

The combination of these changes reduces memory allocation by over 50%. Whilst there is undoubtedly more work we could do here, I have focused on the biggest suspects and the lowest hanging fruit.

Whilst this doesn't help us stop leakage, reducing the amount of memory we use to begin with can only help the stability and future investigations into the leak.

(These numbers are calculated on top of Ruby 2.6.1 which has since been merged in)

## Run this yourself
* Add derailed_benchmarks to the gemfile and bundle outside of Docker
* Copy `environments/production.rb` into `environments/development.rb` and disabled `force_ssl` and comment out `ssl_options`.
* Update docker-compose.yml with
* Comment out the following from `bin/spring`
```
begin
  load File.expand_path('../spring', __FILE__)
rescue LoadError => e
  raise unless e.message.include?('spring')
end
```

* Comment out the following from from bin/spring (this might not be needed anymore) 
```
unless defined?(Spring)
  require 'rubygems'
  require 'bundler'

  lockfile = Bundler::LockfileParser.new(Bundler.default_lockfile.read)
  spring = lockfile.specs.detect { |spec| spec.name == "spring" }
  if spring
    Gem.use_paths Gem.dir, Bundler.bundle_path.to_s, *Gem.path
    gem 'spring', spring.version
    require 'spring/binstub'
  end
end
```
* Change your docker-compose.yml to expose a redis connection port for the tool to boot:

```
  redis_cache:
    image: redis:latest
    command: redis-server
    restart: on-failure
    ports:
      - "6379:6379"
```

3. Run the following steps:
```bash
RAILS_ENV=production bundle exec rake DATABASE_URL=postgresql:does_not_exist --quiet assets:precompile
docker-compose -up
TEST_COUNT=1000 RAILS_ENV=development ALLOW_FILES=teacher-vacancy-service bundle exec derailed exec perf:objects
```

Logging uses memory itself (quite a bit) so you can turn this off by adding `config.lograge.logger =  ActiveSupport::Logger.new('/dev/null')` to your `environments/development.rb`.

### Before
```
allocated memory by gem
-----------------------------------
  83660000  teacher-vacancy-service/app
    568000  teacher-vacancy-service/lib
    536000  other

allocated memory by file
-----------------------------------
  13840000  /Users/xx/sites/dfe/teacher-vacancy-service/app/helpers/date_helper.rb
  11360000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/vacancies/_vacancy.html.haml
   7744000  /Users/xx/sites/dfe/teacher-vacancy-service/app/helpers/application_helper.rb
   7072000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/vacancies/index.html.haml
   7000000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/vacancies/_filters.html.haml
   6800000  /Users/xx/sites/dfe/teacher-vacancy-service/app/presenters/vacancy_presenter.rb
   5800000  /Users/xx/sites/dfe/teacher-vacancy-service/app/helpers/vacancies_helper.rb
   5325000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/layouts/application.html.haml
   4664000  /Users/xx/sites/dfe/teacher-vacancy-service/app/services/vacancy_search_builder.rb
   2064000  /Users/xx/sites/dfe/teacher-vacancy-service/app/controllers/vacancies_controller.rb
   1712000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/kaminari/_page.html.haml
   1600000  /Users/xx/sites/dfe/teacher-vacancy-service/app/presenters/school_presenter.rb
   1152000  /Users/xx/sites/dfe/teacher-vacancy-service/app/presenters/vacancies_presenter.rb
    896000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/shared/_navigation.haml
```

### After
```
allocated memory by gem
-----------------------------------
  36476000  teacher-vacancy-service/app
   6712000  teacher-vacancy-service/lib
    536000  other

allocated memory by file
-----------------------------------
   7000000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/vacancies/_filters.html.haml
   6712000  /Users/xx/sites/dfe/teacher-vacancy-service/lib/logging/colour_log_formatter.rb
   5325000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/layouts/application.html.haml
   4664000  /Users/xx/sites/dfe/teacher-vacancy-service/app/services/vacancy_search_builder.rb
   4280000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/kaminari/_page.html.haml
   2408000  /Users/xx/sites/dfe/teacher-vacancy-service/app/helpers/vacancies_helper.rb
   2144000  /Users/xx/sites/dfe/teacher-vacancy-service/app/controllers/vacancies_controller.rb
   1664000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/vacancies/index.html.haml
    896000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/shared/_navigation.haml
    863000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/shared/_gtag.html.haml
    856000  /Users/xx/sites/dfe/teacher-vacancy-service/app/services/vacancy_filters.rb
    816000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/kaminari/_next_page.html.haml
    784000  /Users/xx/sites/dfe/teacher-vacancy-service/app/models/vacancy.rb
    776000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/kaminari/_last_page.html.haml
    744000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/shared/_open_graph.html.haml
    624000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/shared/_meta.html.haml
    592000  /Users/xx/sites/dfe/teacher-vacancy-service/app/presenters/vacancies_presenter.rb
    544000  /Users/xx/sites/dfe/teacher-vacancy-service/app/views/kaminari/_paginator.html.haml
    536000  /Users/xx/sites/dfe/teacher-vacancy-service/config/environments/development.rb
```

### CODE REVIEW

**Comment by tahb** [comment]
[Investigate very high memory usage for Puma on production](https://trello.com/c/yeyEZCG7/757-investigate-very-high-memory-usage-for-puma-on-production)

**Comment by pezholio** [comment]
@tahb I'm having trouble replicating these instructions. I'm working on `develop`, with the Ruby 2.6.1 changes merged in manually, and I get the error `Your Ruby version is 2.4.1, but your Gemfile specified 2.6.1` I've tried killing and rebuilding my Docker containers, and I still get the same errors, and there's no referecne the 2.4.1 in the source code (Dockerfile, Gemfile etc) anywhere.

**Comment by tahb** [comment]
@pezholio Okay. Since derailed is running outside of Docker you may need to set your local Ruby to 2.6.1, I use `rbenv local 2.6.1`. With that it should hopefully match your Gemfile.

**Comment by pezholio** [comment]
Yeah, I'd done that too, and I still get the Docker errors :/

**Pull request merged**
