### PR TITLE
Chore/amend scraped vacancies

### PR DESCRIPTION
**Pull request by despo**

### CODE REVIEW

**Comment by despo** [comment]
[Updates to scraped vacancies](https://trello.com/c/2QfiFTdY/95-updates-to-scraped-vacancies)

**Comment by tahb** [comment]
Chatted through this change to gather up what it is, why its needed and who it helps.

The scenario for QA on scraped content we'd like to be as follows:

1. vacancy A is scraped
2. vacancy A is content reviewed by Michael & changes are pushed
3. vacancy A is edited by the school that owns it & changes are saved

This PR concerns it self with the second point and how Michael gives us the changes to propagate to production.

We need to ensure that we never overwrite the content set by hiring staff in between the scrape and our update.

**Comment by tahb** [comment]
CI failing:

```
Failures:

  1) Hiring staff can edit a vacancy attempting to edit a draft vacancy redirects to the review vacancy page
     Failure/Error: page.set_rack_session(session_id: session_id)

     TypeError:
       wrong argument type Integer (expected Proc)
     # /usr/local/bundle/gems/capybara-2.15.1/lib/capybara/rack_test/browser.rb:44:in `block in process_and_follow_redirects'
```

Run the same seed locally (199) and it passes.

**Comment by despo** [comment]
@tahb I get this error periodically but I've not come across it in a while.

**Comment by tahb** [comment]
@despo I did some reading and found DatabaseCleaner had a similar issue in Ruby 2.4.0. Long shot but I'm trying to update to Ruby 2.5.1.

https://github.com/DatabaseCleaner/database_cleaner/issues/466

**Pull request merged**
