### PR TITLE
(chore) fix sorting bug

### PR DESCRIPTION
**Pull request by despo**
Switch to will_paginate and ensure it’s included before the elasticsearch-model

### CODE REVIEW

**Comment by despo** [comment]
[bug: sort by posting date doesn't work - job just posted shows as last result (3rd page)](https://trello.com/c/nUnbsNEO/88-bug-sort-by-posting-date-doesnt-work-job-just-posted-shows-as-last-result-3rd-page)

**Comment by tahb** [comment]
Are there any special setup steps for this? I get some very odd behaviour on my existing data:

I have 18 vacancies in my database.

But see:

screen shot 2018-04-24 at 17 28 06


The different pages have random amounts of content.

**Comment by despo** [comment]
@tahb unable to replicate on local, ege is fine - https://tvs.edge.dxw.net

**Comment by tahb** [comment]
In trying to fix the fragile test that kept failing I think I have addressed this issue too: https://github.com/dxw/teacher-vacancy-service/pull/171

**Pull request closed without merging**
