### PR TITLE
Hiring staff UI improvements

### PR DESCRIPTION
**Pull request by lozette**
## Trello card URL:

This PR covers a few cards:
https://trello.com/c/iWZh1bSZ/653-hiring-staff-ui-improvements (@gazaston)
https://trello.com/c/FJE5XW0Y/646-create-new-job-status-draft (@lozette)
https://trello.com/c/UwuesOnr/645-create-new-job-status-pending (@lozette)
https://trello.com/c/YFLoKl9S/647-create-new-job-status-expired (@lozette)

## Changes in this PR:

[Note that this PR does not include adding page view data to the expired and published jobs tabs, or republishing an expired job]

Improve the hiring staff view of their jobs, with tabs to split the jobs into Published | Draft | Pending | Expired. 

For non-JS users the tab contents will be stacked on top of each other.

Associated back-end work, creating new scopes for expired and pending vacancies. 

## Screenshots of UI changes:

screenshot 2018-12-10 at 12 39 30

screenshot 2018-12-10 at 12 39 39

screenshot 2018-12-10 at 12 39 44

Non-JS view

screenshot 2018-12-10 at 12 41 38

### CODE REVIEW

**Comment by lozette** [comment]
[Create new job status: expired](https://trello.com/c/YFLoKl9S/647-create-new-job-status-expired)

**Comment by lozette** [comment]
[Create new job status: expired](https://trello.com/c/YFLoKl9S/647-create-new-job-status-expired)

**Comment by lozette** [comment]
[Create new job status: draft](https://trello.com/c/FJE5XW0Y/646-create-new-job-status-draft)

**Comment by lozette** [comment]
[Create new job status: pending](https://trello.com/c/UwuesOnr/645-create-new-job-status-pending)

**Comment by lozette** [comment]
[Hiring staff UI improvements](https://trello.com/c/iWZh1bSZ/653-hiring-staff-ui-improvements)

**Comment by lozette** [comment]
I am not super happy with cfe494f900796ee9778d7b7241ace3f8f9382a2e - Gaz found a bug with the Published tab (which was showing listed vacancies) - turns out Vacancies#listed includes expired vacancies, and changing the listed scope broke some of the API tests. So I have created a Vacancies#live scope. If this is one scope too many then let me know, and we can maybe do it another way?

**Comment by gazaston** [comment]
@lozette This all looks fine to me, but I wonder if we should hold off on merging until the [republishing story](https://trello.com/c/aiP8rVnL/650-republish-an-expired-job) is complete? Thoughts?

**Comment by tahb** [comment]
[Add data about job posting interactions to hiring staff dashboard to highlight job posting activity](https://trello.com/c/j07qRe5U/651-add-data-about-job-posting-interactions-to-hiring-staff-dashboard-to-highlight-job-posting-activity)

**Pull request merged**
