### PR TITLE
(fix) Add Rollbar access token to rake container definition

### PR DESCRIPTION
**Pull request by robbiepaul**
## Trello card URL:

https://trello.com/c/BoB5c43I/797-add-rollbar-access-token-to-rake-container-definition

## Changes in this PR:

- Add Rollbar access token to rake container definition

## Next steps:

- [x] Terraform deployment required?

### CODE REVIEW

**Comment by robbiepaul** [comment]
[Add Rollbar access token to rake container definition](https://trello.com/c/BoB5c43I/797-add-rollbar-access-token-to-rake-container-definition)

**Comment by tahb** [comment]
Wait a mo

**Comment by tahb** [comment]
I think we might need to pass the rollbar token into every use of this container definition too, as in every block we call: `template = "${file(var.ecs_service_rake_container_definition_file_path)}"`

**Comment by robbiepaul** [comment]
Ahhh, my bad. I'll add that now

**Comment by tahb** [comment]
I manually added this code https://github.com/dxw/teacher-vacancy-service/pull/802/files to this branch to test and got:

```

Error: Error refreshing state: 5 error(s) occurred:

* module.ecs.data.template_file.update_spreadsheets_container_definition: 1 error(s) occurred:

* module.ecs.data.template_file.update_spreadsheets_container_definition: data.template_file.update_spreadsheets_container_definition: failed to render : 66:21: unknown variable accessed: rollbar_access_token
* module.ecs.data.template_file.backfill_audit_data_for_vacancy_publish_events_container_definition: 1 error(s) occurred:

* module.ecs.data.template_file.backfill_audit_data_for_vacancy_publish_events_container_definition: data.template_file.backfill_audit_data_for_vacancy_publish_events_container_definition: failed to render : 66:21: unknown variable accessed: rollbar_access_t
oken
* module.ecs.data.template_file.reindex_vacancies_container_definition: 1 error(s) occurred:

* module.ecs.data.template_file.reindex_vacancies_container_definition: data.template_file.reindex_vacancies_container_definition: failed to render : 66:21: unknown variable accessed: rollbar_access_token
* module.ecs.data.template_file.sessions_trim_container_definition: 1 error(s) occurred:

* module.ecs.data.template_file.sessions_trim_container_definition: data.template_file.sessions_trim_container_definition: failed to render : 66:21: unknown variable accessed: rollbar_access_token
* module.ecs.data.template_file.import_schools_container_definition: 1 error(s) occurred:

* module.ecs.data.template_file.import_schools_container_definition: data.template_file.import_schools_container_definition: failed to render : 66:21: unknown variable accessed: rollbar_access_token
```

Good to get opinions on that script so we can get it to start helping us.

**Comment by robbiepaul** [comment]
Yeah that script is super useful we should get it merged in. 

Pushed up some changes, I ran the script against it and it planned successfully

**Pull request merged**
